# Generated by Django 4.1.7 on 2023-03-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_options_remove_city_user_city_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
    ]
